# Generated by Django 5.2 on 2025-05-25 21:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peticion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('Libro', 'Libro'), ('Manga', 'Manga'), ('Anime', 'Anime'), ('Película', 'Película'), ('Cómic', 'Cómic')], max_length=20)),
                ('autor', models.CharField(blank=True, max_length=100, null=True)),
                ('estudio', models.CharField(blank=True, max_length=100, null=True)),
                ('director', models.CharField(blank=True, max_length=100, null=True)),
                ('editorial', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_lanzamiento', models.DateField(blank=True, null=True)),
                ('imagen', models.ImageField(upload_to='imagenes_productos/')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('fecha_peticion', models.DateField(default=django.utils.timezone.now)),
                ('comentario_admin', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
