# Generated by Django 5.2 on 2025-05-27 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peticiones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peticion',
            name='imagen',
            field=models.URLField(blank=True),
        ),
    ]
