# Generated by Django 5.2 on 2025-06-14 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_customuser_seguidores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='seguidores',
        ),
    ]
