# Generated by Django 5.2 on 2025-06-15 22:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_favorito_customuser_biblioteca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorito',
            name='puntuacion',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
