# Generated by Django 5.2 on 2025-06-14 22:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0003_remove_customuser_seguidores'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='seguidores',
            field=models.ManyToManyField(blank=True, related_name='siguiendo', to=settings.AUTH_USER_MODEL),
        ),
    ]
