# Generated by Django 5.2 on 2025-06-28 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0003_alter_favorito_puntuacion'),
        ('categorias', '0004_customuser_seguidores'),
    ]

    operations = [
    ]
