# Generated by Django 5.2 on 2025-06-30 05:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0004_customuser_seguidores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='seguidores',
            field=models.ManyToManyField(blank=True, related_name='siguiendo_usuarios', to=settings.AUTH_USER_MODEL),
        ),
    ]
