# Generated by Django 5.2 on 2025-06-28 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_reseña_comentario'),
        ('categorias', '0005_merge_20250628_1854'),
    ]

    operations = [
    ]
