# Generated by Django 5.2 on 2025-07-01 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0005_alter_customuser_seguidores'),
        ('categorias', '0006_merge_0002_reseña_comentario_0005_merge_20250628_1854'),
    ]

    operations = [
    ]
